import { sql } from "drizzle-orm";
import { index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const sources = sqliteTable(
  "sources",
  {
    id: text("id").primaryKey(),
    name: text("name").notNull(),
    owner: text("owner").notNull(),
    jurisdictionId: text("jurisdiction_id"),
    jurisdictionName: text("jurisdiction_name").notNull(),
    jurisdictionLevel: text("jurisdiction_level").notNull(),
    connector: text("connector").notNull(),
    connectorVersion: text("connector_version").notNull().default("1"),
    sourceClass: text("source_class").notNull().default("unknown"),
    sourceUrl: text("source_url").notNull(),
    accessMode: text("access_mode").notNull(),
    cadenceMinutes: integer("cadence_minutes").notNull(),
    status: text("status").notNull(),
    lifecycleStages: text("lifecycle_stages", { mode: "json" }).$type<string[]>().notNull(),
    lastCheckedAt: text("last_checked_at"),
    lastSuccessAt: text("last_success_at"),
    lastError: text("last_error"),
    cursor: text("cursor", { mode: "json" }).$type<Record<string, unknown>>(),
    nextDueAt: text("next_due_at"),
    leaseOwner: text("lease_owner"),
    leaseExpiresAt: text("lease_expires_at"),
    sourceReportedTotal: integer("source_reported_total"),
    snapshotComplete: integer("snapshot_complete", { mode: "boolean" }).notNull().default(false),
    lastCompleteSnapshotAt: text("last_complete_snapshot_at"),
    consecutiveFailures: integer("consecutive_failures").notNull().default(0),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    index("sources_jurisdiction_idx").on(table.jurisdictionId),
    index("sources_status_idx").on(table.status),
  ],
);

export const jurisdictions = sqliteTable(
  "jurisdictions",
  {
    id: text("id").primaryKey(),
    censusGovernmentId: text("census_government_id"),
    name: text("name").notNull(),
    governmentType: text("government_type").notNull(),
    registryKind: text("registry_kind").notNull().default("independent-government"),
    state: text("state"),
    fips: text("fips"),
    fipsState: text("fips_state"),
    fipsCounty: text("fips_county"),
    fipsPlace: text("fips_place"),
    parentId: text("parent_id"),
    addressLine1: text("address_line_1"),
    addressLine2: text("address_line_2"),
    city: text("city"),
    postalCode: text("postal_code"),
    website: text("website"),
    politicalCode: text("political_code"),
    functionName: text("function_name"),
    population: integer("population"),
    populationYear: integer("population_year"),
    countyAreaName: text("county_area_name"),
    active: integer("active", { mode: "boolean" }).notNull().default(true),
    sourceUrl: text("source_url"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("jurisdictions_census_uidx").on(table.censusGovernmentId),
    index("jurisdictions_state_type_idx").on(table.state, table.governmentType),
    index("jurisdictions_name_idx").on(table.name),
    index("jurisdictions_state_city_idx").on(table.state, table.city),
  ],
);

export const projects = sqliteTable(
  "projects",
  {
    id: text("id").primaryKey(),
    canonicalKey: text("canonical_key").notNull(),
    title: text("title").notNull(),
    summary: text("summary").notNull().default(""),
    stage: text("stage").notNull(),
    status: text("status").notNull(),
    agency: text("agency").notNull(),
    ownerName: text("owner_name"),
    architectName: text("architect_name"),
    engineerName: text("engineer_name"),
    address: text("address"),
    city: text("city"),
    county: text("county"),
    state: text("state"),
    postalCode: text("postal_code"),
    latitude: real("latitude"),
    longitude: real("longitude"),
    estimatedValue: real("estimated_value"),
    postedAt: text("posted_at"),
    bidDate: text("bid_date"),
    awardDate: text("award_date"),
    firstSeenAt: text("first_seen_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    lastSeenAt: text("last_seen_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("projects_canonical_key_uidx").on(table.canonicalKey),
    index("projects_stage_idx").on(table.stage),
    index("projects_state_idx").on(table.state),
    index("projects_bid_date_idx").on(table.bidDate),
  ],
);

export const projectSources = sqliteTable(
  "project_sources",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
    sourceId: text("source_id").notNull().references(() => sources.id, { onDelete: "cascade" }),
    sourceRecordId: text("source_record_id").notNull(),
    sourceUrl: text("source_url").notNull(),
    rawHash: text("raw_hash"),
    confidence: text("confidence").notNull(),
    firstSeenAt: text("first_seen_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    lastSeenAt: text("last_seen_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("project_sources_record_uidx").on(table.sourceId, table.sourceRecordId),
    index("project_sources_project_idx").on(table.projectId),
  ],
);

export const sourceMonitors = sqliteTable(
  "source_monitors",
  {
    id: text("id").primaryKey(),
    sourceId: text("source_id").notNull().references(() => sources.id, { onDelete: "cascade" }),
    ownerKey: text("owner_key").notNull(),
    name: text("name").notNull(),
    publisher: text("publisher").notNull(),
    jurisdiction: text("jurisdiction").notNull(),
    city: text("city"),
    state: text("state"),
    sourceType: text("source_type").notNull(),
    feedUrl: text("feed_url").notNull(),
    feedFormat: text("feed_format").notNull().default("auto"),
    cadenceMinutes: integer("cadence_minutes").notNull().default(1440),
    status: text("status").notNull().default("active"),
    nextDueAt: text("next_due_at"),
    lastCheckedAt: text("last_checked_at"),
    lastSuccessAt: text("last_success_at"),
    lastError: text("last_error"),
    consecutiveFailures: integer("consecutive_failures").notNull().default(0),
    createdBy: text("created_by").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("source_monitors_source_uidx").on(table.sourceId),
    uniqueIndex("source_monitors_owner_feed_uidx").on(table.ownerKey, table.feedUrl),
    index("source_monitors_due_idx").on(table.status, table.nextDueAt),
    index("source_monitors_owner_idx").on(table.ownerKey, table.updatedAt),
  ],
);

export const sourcePostingCandidates = sqliteTable(
  "source_posting_candidates",
  {
    id: text("id").primaryKey(),
    monitorId: text("monitor_id").notNull().references(() => sourceMonitors.id, { onDelete: "cascade" }),
    projectId: text("project_id").references(() => projects.id, { onDelete: "set null" }),
    sourceRecordId: text("source_record_id").notNull(),
    title: text("title").notNull(),
    summary: text("summary").notNull().default(""),
    sourceUrl: text("source_url").notNull(),
    publisher: text("publisher").notNull(),
    city: text("city"),
    state: text("state"),
    postedAt: text("posted_at"),
    bidDate: text("bid_date"),
    documentUrl: text("document_url"),
    documentName: text("document_name"),
    contactName: text("contact_name"),
    contactEmail: text("contact_email"),
    contactPhone: text("contact_phone"),
    submissionUrl: text("submission_url"),
    tradeTags: text("trade_tags", { mode: "json" }).$type<string[]>().notNull(),
    opportunityType: text("opportunity_type").notNull(),
    status: text("status").notNull().default("needs-review"),
    readinessReasons: text("readiness_reasons", { mode: "json" }).$type<string[]>().notNull(),
    evidence: text("evidence", { mode: "json" }).$type<Record<string, unknown>>().notNull(),
    firstSeenAt: text("first_seen_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    lastSeenAt: text("last_seen_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    reviewedAt: text("reviewed_at"),
    reviewedBy: text("reviewed_by"),
  },
  (table) => [
    uniqueIndex("source_posting_candidates_record_uidx").on(table.monitorId, table.sourceRecordId),
    uniqueIndex("source_posting_candidates_project_uidx").on(table.projectId),
    index("source_posting_candidates_monitor_status_idx").on(table.monitorId, table.status, table.lastSeenAt),
    index("source_posting_candidates_bid_date_idx").on(table.status, table.bidDate),
  ],
);

export const projectOpportunityVerifications = sqliteTable(
  "project_opportunity_verifications",
  {
    projectId: text("project_id").primaryKey().references(() => projects.id, { onDelete: "cascade" }),
    candidateId: text("candidate_id").notNull().references(() => sourcePostingCandidates.id, { onDelete: "cascade" }),
    opportunityType: text("opportunity_type").notNull(),
    verificationStatus: text("verification_status").notNull(),
    acceptingBids: integer("accepting_bids", { mode: "boolean" }).notNull().default(false),
    submissionUrl: text("submission_url"),
    evidence: text("evidence", { mode: "json" }).$type<Record<string, unknown>>().notNull(),
    verifiedAt: text("verified_at"),
    verifiedBy: text("verified_by"),
    lastCheckedAt: text("last_checked_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("project_opportunity_verifications_candidate_uidx").on(table.candidateId),
    index("project_opportunity_verifications_status_idx").on(
      table.verificationStatus,
      table.acceptingBids,
    ),
  ],
);

export const projectIdentifiers = sqliteTable(
  "project_identifiers",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
    identifierType: text("identifier_type").notNull(),
    identifierValue: text("identifier_value").notNull(),
    sourceId: text("source_id").references(() => sources.id),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("project_identifiers_uidx").on(table.identifierType, table.identifierValue),
    index("project_identifiers_project_idx").on(table.projectId),
  ],
);

export const organizations = sqliteTable(
  "organizations",
  {
    id: text("id").primaryKey(),
    normalizedName: text("normalized_name").notNull(),
    displayName: text("display_name").notNull(),
    organizationType: text("organization_type").notNull(),
    uei: text("uei"),
    website: text("website"),
    city: text("city"),
    state: text("state"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [uniqueIndex("organizations_name_uidx").on(table.normalizedName)],
);

export const projectParticipants = sqliteTable(
  "project_participants",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
    organizationId: text("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
    role: text("role").notNull(),
    participationStatus: text("participation_status").notNull(),
    sourceId: text("source_id").references(() => sources.id),
    firstSeenAt: text("first_seen_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    lastSeenAt: text("last_seen_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("project_participants_role_uidx").on(table.projectId, table.organizationId, table.role),
    index("project_participants_org_idx").on(table.organizationId),
  ],
);

export const documentBlobs = sqliteTable(
  "document_blobs",
  {
    contentHash: text("content_hash").primaryKey(),
    objectKey: text("object_key").notNull(),
    bytes: integer("bytes").notNull(),
    mimeType: text("mime_type").notNull(),
    extension: text("extension"),
    storageStatus: text("storage_status").notNull().default("ready"),
    securityStatus: text("security_status").notNull().default("unscanned"),
    r2Etag: text("r2_etag"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    lastVerifiedAt: text("last_verified_at"),
  },
  (table) => [
    uniqueIndex("document_blobs_object_key_uidx").on(table.objectKey),
    index("document_blobs_security_idx").on(table.securityStatus, table.storageStatus),
  ],
);

export const documents = sqliteTable(
  "documents",
  {
    id: text("id").primaryKey(),
    projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
    sourceId: text("source_id").notNull().references(() => sources.id),
    name: text("name").notNull(),
    documentType: text("document_type").notNull(),
    description: text("description").notNull().default(""),
    discipline: text("discipline"),
    sheetNumbers: text("sheet_numbers", { mode: "json" }).$type<string[]>(),
    keywords: text("keywords", { mode: "json" }).$type<string[]>(),
    sourceUrl: text("source_url").notNull(),
    accessMode: text("access_mode").notNull(),
    visibility: text("visibility").notNull().default("workspace"),
    licenseCode: text("license_code"),
    licenseUrl: text("license_url"),
    redistributionAllowed: integer("redistribution_allowed", { mode: "boolean" }).notNull().default(false),
    provenance: text("provenance", { mode: "json" }).$type<Record<string, unknown>>(),
    ingestionMethod: text("ingestion_method").notNull().default("source-link"),
    processingStatus: text("processing_status").notNull().default("metadata-only"),
    processingError: text("processing_error"),
    searchText: text("search_text").notNull().default(""),
    mimeType: text("mime_type"),
    contentHash: text("content_hash"),
    objectKey: text("object_key"),
    fileName: text("file_name"),
    bytes: integer("bytes"),
    uploadedBy: text("uploaded_by"),
    publishedAt: text("published_at"),
    firstSeenAt: text("first_seen_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    lastSeenAt: text("last_seen_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("documents_source_url_uidx").on(table.projectId, table.sourceUrl),
    index("documents_project_idx").on(table.projectId),
    index("documents_type_idx").on(table.documentType),
    index("documents_processing_idx").on(table.processingStatus),
    index("documents_visibility_idx").on(
      table.visibility,
      table.accessMode,
      table.redistributionAllowed,
    ),
  ],
);

export const documentVersions = sqliteTable(
  "document_versions",
  {
    id: text("id").primaryKey(),
    documentId: text("document_id").notNull().references(() => documents.id, { onDelete: "cascade" }),
    sourceVersionId: text("source_version_id"),
    normalizedUrl: text("normalized_url").notNull(),
    contentHash: text("content_hash"),
    objectKey: text("object_key"),
    mimeType: text("mime_type"),
    extension: text("extension"),
    bytes: integer("bytes"),
    fileName: text("file_name"),
    accessMode: text("access_mode").notNull(),
    archivePolicy: text("archive_policy").notNull(),
    retrievalStatus: text("retrieval_status").notNull(),
    ingestionMethod: text("ingestion_method").notNull().default("source-link"),
    processingStatus: text("processing_status").notNull().default("metadata-only"),
    processingError: text("processing_error"),
    createdBy: text("created_by"),
    authoritative: integer("authoritative", { mode: "boolean" }).notNull().default(true),
    postedAt: text("posted_at"),
    retrievedAt: text("retrieved_at"),
    supersedesId: text("supersedes_id"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("document_versions_hash_uidx").on(table.documentId, table.contentHash),
    index("document_versions_document_idx").on(table.documentId),
  ],
);

export const documentExtractions = sqliteTable(
  "document_extractions",
  {
    id: text("id").primaryKey(),
    documentVersionId: text("document_version_id").notNull().references(() => documentVersions.id, { onDelete: "cascade" }),
    sourceHash: text("source_hash").notNull(),
    extractor: text("extractor").notNull(),
    extractorVersion: text("extractor_version").notNull(),
    method: text("method").notNull(),
    status: text("status").notNull(),
    language: text("language"),
    pages: integer("pages"),
    confidence: real("confidence"),
    textObjectKey: text("text_object_key"),
    layoutObjectKey: text("layout_object_key"),
    error: text("error"),
    indexedAt: text("indexed_at"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("document_extractions_version_uidx").on(
      table.documentVersionId,
      table.extractor,
      table.extractorVersion,
    ),
    index("document_extractions_status_idx").on(table.status),
  ],
);

export const documentChunks = sqliteTable(
  "document_chunks",
  {
    id: text("id").primaryKey(),
    extractionId: text("extraction_id").notNull().references(() => documentExtractions.id, { onDelete: "cascade" }),
    projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
    documentVersionId: text("document_version_id").notNull().references(() => documentVersions.id, { onDelete: "cascade" }),
    pageStart: integer("page_start"),
    pageEnd: integer("page_end"),
    chunkOrder: integer("chunk_order").notNull(),
    chunkText: text("chunk_text").notNull(),
  },
  (table) => [
    uniqueIndex("document_chunks_order_uidx").on(table.extractionId, table.chunkOrder),
    index("document_chunks_project_idx").on(table.projectId),
  ],
);

export const projectEvents = sqliteTable(
  "project_events",
  {
    id: text("id").primaryKey(),
    projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
    sourceId: text("source_id").notNull().references(() => sources.id),
    eventType: text("event_type").notNull(),
    stage: text("stage").notNull(),
    title: text("title").notNull(),
    occurredAt: text("occurred_at").notNull(),
    payload: text("payload", { mode: "json" }).$type<Record<string, unknown>>(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    index("project_events_project_idx").on(table.projectId),
    index("project_events_occurred_idx").on(table.occurredAt),
  ],
);

export const ingestionRuns = sqliteTable(
  "ingestion_runs",
  {
    id: text("id").primaryKey(),
    sourceId: text("source_id").notNull().references(() => sources.id),
    status: text("status").notNull(),
    startedAt: text("started_at").notNull(),
    finishedAt: text("finished_at"),
    recordsRead: integer("records_read").notNull().default(0),
    projectsCreated: integer("projects_created").notNull().default(0),
    projectsUpdated: integer("projects_updated").notNull().default(0),
    documentsFound: integer("documents_found").notNull().default(0),
    trigger: text("trigger").notNull().default("scheduled"),
    pagesRead: integer("pages_read").notNull().default(0),
    cursorBefore: text("cursor_before", { mode: "json" }).$type<Record<string, unknown>>(),
    cursorAfter: text("cursor_after", { mode: "json" }).$type<Record<string, unknown>>(),
    snapshotComplete: integer("snapshot_complete", { mode: "boolean" }).notNull().default(false),
    metrics: text("metrics", { mode: "json" }).$type<Record<string, unknown>>(),
    error: text("error"),
  },
  (table) => [index("ingestion_runs_source_started_idx").on(table.sourceId, table.startedAt)],
);

export const coverageCells = sqliteTable(
  "coverage_cells",
  {
    id: text("id").primaryKey(),
    jurisdictionId: text("jurisdiction_id").notNull().references(() => jurisdictions.id, { onDelete: "cascade" }),
    sourceClass: text("source_class").notNull(),
    lifecycleStage: text("lifecycle_stage").notNull(),
    coverageState: text("coverage_state").notNull(),
    sourceId: text("source_id").references(() => sources.id),
    publicDisclosureRule: text("public_disclosure_rule"),
    lastAssessedAt: text("last_assessed_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    note: text("note"),
  },
  (table) => [
    uniqueIndex("coverage_cells_uidx").on(
      table.jurisdictionId,
      table.sourceClass,
      table.lifecycleStage,
    ),
    index("coverage_cells_state_idx").on(table.coverageState),
  ],
);

export const coverageEvidence = sqliteTable(
  "coverage_evidence",
  {
    id: text("id").primaryKey(),
    jurisdictionId: text("jurisdiction_id").notNull().references(() => jurisdictions.id, { onDelete: "cascade" }),
    sourceClass: text("source_class").notNull(),
    lifecycleStage: text("lifecycle_stage").notNull(),
    sourceId: text("source_id").notNull().references(() => sources.id),
    evidenceState: text("evidence_state").notNull(),
    lastAssessedAt: text("last_assessed_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    note: text("note"),
  },
  (table) => [
    uniqueIndex("coverage_evidence_uidx").on(
      table.jurisdictionId,
      table.sourceClass,
      table.lifecycleStage,
      table.sourceId,
    ),
    index("coverage_evidence_source_state_idx").on(
      table.sourceId,
      table.evidenceState,
    ),
    index("coverage_evidence_cell_idx").on(
      table.jurisdictionId,
      table.sourceClass,
      table.lifecycleStage,
    ),
  ],
);

export const projectJurisdictions = sqliteTable(
  "project_jurisdictions",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
    jurisdictionId: text("jurisdiction_id").notNull().references(() => jurisdictions.id, { onDelete: "cascade" }),
    relationship: text("relationship").notNull().default("site"),
    matchMethod: text("match_method").notNull(),
    confidence: real("confidence").notNull(),
    sourceUrl: text("source_url"),
    observedAt: text("observed_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    verificationStatus: text("verification_status").notNull().default("unverified"),
    verifiedAt: text("verified_at"),
    verifiedBy: text("verified_by"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("project_jurisdictions_relationship_uidx").on(
      table.projectId,
      table.jurisdictionId,
      table.relationship,
    ),
    index("project_jurisdictions_project_idx").on(table.projectId),
    index("project_jurisdictions_jurisdiction_idx").on(table.jurisdictionId),
  ],
);

export const jurisdictionDiscoveryJobs = sqliteTable(
  "jurisdiction_discovery_jobs",
  {
    id: text("id").primaryKey(),
    jurisdictionId: text("jurisdiction_id").notNull().references(() => jurisdictions.id, { onDelete: "cascade" }),
    status: text("status").notNull().default("queued"),
    priority: integer("priority").notNull().default(0),
    requiredSourceClasses: text("required_source_classes", { mode: "json" }).$type<string[]>().notNull(),
    completedSourceClasses: text("completed_source_classes", { mode: "json" }).$type<string[]>().notNull(),
    currentSourceClass: text("current_source_class"),
    connectorFamily: text("connector_family"),
    sourceCandidatesFound: integer("source_candidates_found").notNull().default(0),
    connectedSources: integer("connected_sources").notNull().default(0),
    loadedProjects: integer("loaded_projects").notNull().default(0),
    indexedDocuments: integer("indexed_documents").notNull().default(0),
    cursor: text("cursor", { mode: "json" }).$type<Record<string, unknown>>(),
    attemptCount: integer("attempt_count").notNull().default(0),
    leaseOwner: text("lease_owner"),
    leaseExpiresAt: text("lease_expires_at"),
    nextRunAt: text("next_run_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    lastStartedAt: text("last_started_at"),
    lastFinishedAt: text("last_finished_at"),
    lastSuccessAt: text("last_success_at"),
    error: text("error"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("jurisdiction_discovery_jobs_jurisdiction_uidx").on(table.jurisdictionId),
    index("jurisdiction_discovery_jobs_due_idx").on(table.status, table.nextRunAt, table.priority),
    index("jurisdiction_discovery_jobs_lease_idx").on(table.leaseExpiresAt),
  ],
);

export const jurisdictionMetrics = sqliteTable(
  "jurisdiction_metrics",
  {
    jurisdictionId: text("jurisdiction_id").primaryKey().references(() => jurisdictions.id, { onDelete: "cascade" }),
    loadedProjects: integer("loaded_projects").notNull().default(0),
    planningProjects: integer("planning_projects").notNull().default(0),
    designProjects: integer("design_projects").notNull().default(0),
    permittingProjects: integer("permitting_projects").notNull().default(0),
    biddingProjects: integer("bidding_projects").notNull().default(0),
    bidOpenedProjects: integer("bid_opened_projects").notNull().default(0),
    awardedProjects: integer("awarded_projects").notNull().default(0),
    completedProjects: integer("completed_projects").notNull().default(0),
    cancelledProjects: integer("cancelled_projects").notNull().default(0),
    unclassifiedProjects: integer("unclassified_projects").notNull().default(0),
    publicDocuments: integer("public_documents").notNull().default(0),
    indexedDocuments: integer("indexed_documents").notNull().default(0),
    connectedSourceClasses: integer("connected_source_classes").notNull().default(0),
    requiredSourceClasses: integer("required_source_classes").notNull().default(7),
    lastProjectAt: text("last_project_at"),
    refreshedAt: text("refreshed_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    index("jurisdiction_metrics_projects_idx").on(table.loadedProjects),
    index("jurisdiction_metrics_connection_idx").on(
      table.connectedSourceClasses,
      table.requiredSourceClasses,
    ),
  ],
);

export const datasetCandidates = sqliteTable(
  "dataset_candidates",
  {
    id: text("id").primaryKey(),
    catalog: text("catalog").notNull(),
    publisher: text("publisher"),
    jurisdictionName: text("jurisdiction_name"),
    title: text("title").notNull(),
    description: text("description"),
    sourceUrl: text("source_url").notNull(),
    apiUrl: text("api_url"),
    sourceClass: text("source_class").notNull(),
    status: text("status").notNull().default("candidate"),
    portalFamily: text("portal_family"),
    portalConfidence: real("portal_confidence"),
    portalClassifierVersion: text("portal_classifier_version"),
    portalEvidence: text("portal_evidence", { mode: "json" }).$type<Record<string, unknown>>(),
    portalNetworkAccessStatus: text("portal_network_access_status")
      .notNull()
      .default("disabled-until-reviewed"),
    portalReviewStatus: text("portal_review_status").notNull().default("unverified"),
    portalConnectionState: text("portal_connection_state")
      .notNull()
      .default("not-connected"),
    classifiedAt: text("classified_at"),
    discoveredAt: text("discovered_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    lastVerifiedAt: text("last_verified_at"),
  },
  (table) => [
    uniqueIndex("dataset_candidates_catalog_uidx").on(table.catalog, table.sourceUrl),
    index("dataset_candidates_status_idx").on(table.status, table.sourceClass),
    index("dataset_candidates_portal_review_idx").on(
      table.portalReviewStatus,
      table.portalFamily,
    ),
  ],
);

export const datasetCandidateJurisdictions = sqliteTable(
  "dataset_candidate_jurisdictions",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    candidateId: text("candidate_id").notNull().references(() => datasetCandidates.id, { onDelete: "cascade" }),
    jurisdictionId: text("jurisdiction_id").notNull().references(() => jurisdictions.id, { onDelete: "cascade" }),
    matchMethod: text("match_method").notNull(),
    confidence: real("confidence").notNull(),
    evidenceUrl: text("evidence_url"),
    verificationStatus: text("verification_status").notNull().default("unverified"),
    observedAt: text("observed_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    verifiedAt: text("verified_at"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("dataset_candidate_jurisdictions_uidx").on(
      table.candidateId,
      table.jurisdictionId,
    ),
    index("dataset_candidate_jurisdictions_candidate_idx").on(table.candidateId),
    index("dataset_candidate_jurisdictions_jurisdiction_idx").on(table.jurisdictionId),
  ],
);

export const supplierProfiles = sqliteTable(
  "supplier_profiles",
  {
    id: text("id").primaryKey(),
    legalName: text("legal_name").notNull(),
    website: text("website").notNull(),
    addressLine1: text("address_line_1").notNull(),
    city: text("city").notNull(),
    state: text("state").notNull(),
    postalCode: text("postal_code").notNull(),
    publicPhone: text("public_phone"),
    publicEmail: text("public_email"),
    products: text("products", { mode: "json" }).$type<string[]>().notNull(),
    sourceUrl: text("source_url"),
    verifiedAt: text("verified_at"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [uniqueIndex("supplier_profiles_name_uidx").on(table.legalName)],
);

export const portalAccounts = sqliteTable(
  "portal_accounts",
  {
    id: text("id").primaryKey(),
    supplierProfileId: text("supplier_profile_id").notNull().references(() => supplierProfiles.id),
    sourceId: text("source_id").references(() => sources.id),
    portalFamily: text("portal_family").notNull(),
    jurisdictionName: text("jurisdiction_name").notNull(),
    registrationUrl: text("registration_url").notNull(),
    loginUrl: text("login_url"),
    usernameEmail: text("username_email"),
    credentialReference: text("credential_reference"),
    status: text("status").notNull().default("not-started"),
    verificationStatus: text("verification_status").notNull().default("not-started"),
    termsAcceptedAt: text("terms_accepted_at"),
    lastCheckedAt: text("last_checked_at"),
    note: text("note"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("portal_accounts_profile_url_uidx").on(table.supplierProfileId, table.registrationUrl),
    index("portal_accounts_status_idx").on(table.status, table.verificationStatus),
  ],
);

export const portalRegistrationTasks = sqliteTable(
  "portal_registration_tasks",
  {
    id: text("id").primaryKey(),
    portalAccountId: text("portal_account_id").notNull().references(() => portalAccounts.id, { onDelete: "cascade" }),
    status: text("status").notNull().default("queued"),
    requiredFields: text("required_fields", { mode: "json" }).$type<string[]>().notNull(),
    blockingReason: text("blocking_reason"),
    nextAction: text("next_action"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [index("portal_registration_tasks_status_idx").on(table.status)],
);

export const coverageLedger = sqliteTable(
  "coverage_ledger",
  {
    id: text("id").primaryKey(),
    governmentId: text("government_id").notNull(),
    governmentName: text("government_name").notNull(),
    governmentType: text("government_type").notNull(),
    state: text("state"),
    lifecycleStage: text("lifecycle_stage").notNull(),
    coverageState: text("coverage_state").notNull(),
    sourceId: text("source_id").references(() => sources.id),
    publicDisclosureRule: text("public_disclosure_rule"),
    checkedAt: text("checked_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    note: text("note"),
  },
  (table) => [
    uniqueIndex("coverage_government_stage_uidx").on(table.governmentId, table.lifecycleStage),
    index("coverage_state_status_idx").on(table.state, table.coverageState),
  ],
);

export const contacts = sqliteTable(
  "contacts",
  {
    id: text("id").primaryKey(),
    canonicalKey: text("canonical_key").notNull(),
    organizationId: text("organization_id").references(() => organizations.id, { onDelete: "set null" }),
    contactType: text("contact_type").notNull().default("person"),
    displayName: text("display_name").notNull(),
    firstName: text("first_name"),
    lastName: text("last_name"),
    jobTitle: text("job_title"),
    email: text("email"),
    normalizedEmail: text("normalized_email"),
    phone: text("phone"),
    phoneExtension: text("phone_extension"),
    linkedinUrl: text("linkedin_url"),
    city: text("city"),
    state: text("state"),
    country: text("country").notNull().default("US"),
    sourceId: text("source_id").references(() => sources.id, { onDelete: "set null" }),
    sourceRecordId: text("source_record_id"),
    sourceUrl: text("source_url"),
    provenance: text("provenance", { mode: "json" }).$type<Record<string, unknown>>(),
    confidence: real("confidence"),
    verificationStatus: text("verification_status").notNull().default("unverified"),
    emailVerificationStatus: text("email_verification_status").notNull().default("unknown"),
    phoneVerificationStatus: text("phone_verification_status").notNull().default("unknown"),
    verifiedAt: text("verified_at"),
    verifiedBy: text("verified_by"),
    firstSeenAt: text("first_seen_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    lastSeenAt: text("last_seen_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("contacts_canonical_key_uidx").on(table.canonicalKey),
    uniqueIndex("contacts_source_record_uidx").on(table.sourceId, table.sourceRecordId),
    index("contacts_organization_idx").on(table.organizationId),
    index("contacts_email_idx").on(table.normalizedEmail),
    index("contacts_verification_idx").on(table.verificationStatus),
  ],
);

export const projectContacts = sqliteTable(
  "project_contacts",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
    contactId: text("contact_id").notNull().references(() => contacts.id, { onDelete: "cascade" }),
    organizationId: text("organization_id").references(() => organizations.id, { onDelete: "set null" }),
    role: text("role").notNull(),
    roleSourceText: text("role_source_text"),
    relationshipStatus: text("relationship_status").notNull().default("observed"),
    isPrimary: integer("is_primary", { mode: "boolean" }).notNull().default(false),
    isDecisionMaker: integer("is_decision_maker", { mode: "boolean" }).notNull().default(false),
    sourceId: text("source_id").references(() => sources.id, { onDelete: "set null" }),
    sourceRecordId: text("source_record_id"),
    sourceUrl: text("source_url"),
    provenance: text("provenance", { mode: "json" }).$type<Record<string, unknown>>(),
    confidence: real("confidence"),
    verificationStatus: text("verification_status").notNull().default("unverified"),
    verifiedAt: text("verified_at"),
    verifiedBy: text("verified_by"),
    firstSeenAt: text("first_seen_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    lastSeenAt: text("last_seen_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("project_contacts_role_uidx").on(table.projectId, table.contactId, table.role),
    index("project_contacts_project_role_idx").on(table.projectId, table.role),
    index("project_contacts_contact_idx").on(table.contactId),
    index("project_contacts_organization_idx").on(table.organizationId),
  ],
);

export const savedSearches = sqliteTable(
  "saved_searches",
  {
    id: text("id").primaryKey(),
    supplierProfileId: text("supplier_profile_id").notNull().references(() => supplierProfiles.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    queryText: text("query_text"),
    keywords: text("keywords", { mode: "json" }).$type<string[]>().notNull(),
    matchMode: text("match_mode").notNull().default("any"),
    stages: text("stages", { mode: "json" }).$type<string[]>().notNull(),
    states: text("states", { mode: "json" }).$type<string[]>().notNull(),
    locationQuery: text("location_query"),
    projectTypes: text("project_types", { mode: "json" }).$type<string[]>(),
    masterFormatCodes: text("master_format_codes", { mode: "json" }).$type<string[]>(),
    productTerms: text("product_terms", { mode: "json" }).$type<string[]>(),
    filters: text("filters", { mode: "json" }).$type<Record<string, unknown>>(),
    status: text("status").notNull().default("active"),
    alertEnabled: integer("alert_enabled", { mode: "boolean" }).notNull().default(false),
    alertCadenceMinutes: integer("alert_cadence_minutes"),
    alertDestination: text("alert_destination"),
    nextRunAt: text("next_run_at"),
    lastRunAt: text("last_run_at"),
    lastResultCount: integer("last_result_count"),
    createdBy: text("created_by"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("saved_searches_profile_name_uidx").on(table.supplierProfileId, table.name),
    index("saved_searches_due_idx").on(table.status, table.alertEnabled, table.nextRunAt),
  ],
);

export const bidOpportunities = sqliteTable(
  "bid_opportunities",
  {
    id: text("id").primaryKey(),
    supplierProfileId: text("supplier_profile_id").notNull().references(() => supplierProfiles.id, { onDelete: "cascade" }),
    ownerKey: text("owner_key").notNull().default("legacy-workspace"),
    projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
    savedSearchId: text("saved_search_id").references(() => savedSearches.id, { onDelete: "set null" }),
    scopeKey: text("scope_key").notNull().default("primary"),
    status: text("status").notNull().default("new"),
    priority: text("priority").notNull().default("normal"),
    fitScore: real("fit_score"),
    projectTitleSnapshot: text("project_title_snapshot").notNull(),
    projectStageSnapshot: text("project_stage_snapshot").notNull(),
    productMatches: text("product_matches", { mode: "json" }).$type<string[]>(),
    scopeSummary: text("scope_summary"),
    decision: text("decision").notNull().default("undecided"),
    decisionReason: text("decision_reason"),
    assignedTo: text("assigned_to"),
    bidDueAt: text("bid_due_at"),
    expectedValue: real("expected_value"),
    currency: text("currency").notNull().default("USD"),
    sourceId: text("source_id").references(() => sources.id, { onDelete: "set null" }),
    sourceUrl: text("source_url"),
    provenance: text("provenance", { mode: "json" }).$type<Record<string, unknown>>(),
    confidence: real("confidence"),
    verifiedAt: text("verified_at"),
    discoveredAt: text("discovered_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("bid_opportunities_scope_uidx").on(
      table.supplierProfileId,
      table.ownerKey,
      table.projectId,
      table.scopeKey,
    ),
    index("bid_opportunities_pipeline_idx").on(table.supplierProfileId, table.status, table.bidDueAt),
    index("bid_opportunities_owner_project_idx").on(table.ownerKey, table.projectId),
    index("bid_opportunities_project_idx").on(table.projectId),
    index("bid_opportunities_saved_search_idx").on(table.savedSearchId),
  ],
);

export const bidPackages = sqliteTable(
  "bid_packages",
  {
    id: text("id").primaryKey(),
    bidOpportunityId: text("bid_opportunity_id").notNull().references(() => bidOpportunities.id, { onDelete: "cascade" }),
    ownerKey: text("owner_key").notNull().default("legacy-workspace"),
    packageNumber: text("package_number").notNull(),
    version: integer("version").notNull().default(1),
    supersedesPackageId: text("supersedes_package_id"),
    title: text("title").notNull(),
    status: text("status").notNull().default("draft"),
    scopeDescription: text("scope_description"),
    currency: text("currency").notNull().default("USD"),
    directCost: real("direct_cost").notNull().default(0),
    subtotal: real("subtotal").notNull().default(0),
    tax: real("tax").notNull().default(0),
    total: real("total").notNull().default(0),
    validUntil: text("valid_until"),
    coverMessage: text("cover_message"),
    assumptions: text("assumptions", { mode: "json" }).$type<string[]>(),
    exclusions: text("exclusions", { mode: "json" }).$type<string[]>(),
    terms: text("terms", { mode: "json" }).$type<Record<string, unknown>>(),
    requiresApproval: integer("requires_approval", { mode: "boolean" }).notNull().default(true),
    approvalStatus: text("approval_status").notNull().default("pending"),
    approvedBy: text("approved_by"),
    approvedAt: text("approved_at"),
    approvalNote: text("approval_note"),
    contentHash: text("content_hash"),
    finalizedAt: text("finalized_at"),
    lockedAt: text("locked_at"),
    createdBy: text("created_by"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("bid_packages_version_uidx").on(
      table.bidOpportunityId,
      table.ownerKey,
      table.packageNumber,
      table.version,
    ),
    index("bid_packages_status_idx").on(table.bidOpportunityId, table.status),
    index("bid_packages_owner_idx").on(table.ownerKey, table.updatedAt),
    index("bid_packages_approval_idx").on(table.approvalStatus),
  ],
);

export const bidLineItems = sqliteTable(
  "bid_line_items",
  {
    id: text("id").primaryKey(),
    bidPackageId: text("bid_package_id").notNull().references(() => bidPackages.id, { onDelete: "cascade" }),
    lineNumber: integer("line_number").notNull(),
    itemType: text("item_type").notNull().default("product"),
    masterFormatCode: text("master_format_code"),
    manufacturer: text("manufacturer"),
    sku: text("sku"),
    description: text("description").notNull(),
    quantity: real("quantity").notNull(),
    unit: text("unit").notNull(),
    unitCost: real("unit_cost"),
    unitPrice: real("unit_price").notNull(),
    markupPercent: real("markup_percent"),
    amount: real("amount").notNull(),
    taxable: integer("taxable", { mode: "boolean" }).notNull().default(false),
    isAlternate: integer("is_alternate", { mode: "boolean" }).notNull().default(false),
    alternateGroup: text("alternate_group"),
    notes: text("notes"),
    sourceDocumentId: text("source_document_id").references(() => documents.id, { onDelete: "set null" }),
    sourcePage: integer("source_page"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("bid_line_items_number_uidx").on(table.bidPackageId, table.lineNumber),
    index("bid_line_items_masterformat_idx").on(table.masterFormatCode),
    index("bid_line_items_source_document_idx").on(table.sourceDocumentId),
  ],
);

export const bidPackageAttachments = sqliteTable(
  "bid_package_attachments",
  {
    id: text("id").primaryKey(),
    bidPackageId: text("bid_package_id").notNull().references(() => bidPackages.id, { onDelete: "cascade" }),
    documentId: text("document_id").references(() => documents.id, { onDelete: "set null" }),
    attachmentType: text("attachment_type").notNull(),
    fileName: text("file_name").notNull(),
    mimeType: text("mime_type"),
    bytes: integer("bytes"),
    objectKey: text("object_key"),
    sourceUrl: text("source_url"),
    contentHash: text("content_hash"),
    included: integer("included", { mode: "boolean" }).notNull().default(true),
    createdBy: text("created_by"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("bid_package_attachments_hash_uidx").on(table.bidPackageId, table.contentHash),
    index("bid_package_attachments_package_idx").on(table.bidPackageId, table.attachmentType),
    index("bid_package_attachments_document_idx").on(table.documentId),
  ],
);

export const bidRecipients = sqliteTable(
  "bid_recipients",
  {
    id: text("id").primaryKey(),
    bidPackageId: text("bid_package_id").notNull().references(() => bidPackages.id, { onDelete: "cascade" }),
    projectContactId: integer("project_contact_id").references(() => projectContacts.id, { onDelete: "set null" }),
    contactId: text("contact_id").references(() => contacts.id, { onDelete: "set null" }),
    organizationId: text("organization_id").references(() => organizations.id, { onDelete: "set null" }),
    portalAccountId: text("portal_account_id").references(() => portalAccounts.id, { onDelete: "set null" }),
    recipientRole: text("recipient_role").notNull(),
    deliveryChannel: text("delivery_channel").notNull(),
    destination: text("destination").notNull(),
    normalizedDestination: text("normalized_destination").notNull(),
    isPrimary: integer("is_primary", { mode: "boolean" }).notNull().default(false),
    status: text("status").notNull().default("pending"),
    verificationStatus: text("verification_status").notNull().default("unverified"),
    verifiedAt: text("verified_at"),
    verifiedBy: text("verified_by"),
    consentBasis: text("consent_basis"),
    lastDeliveryAt: text("last_delivery_at"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("bid_recipients_destination_uidx").on(
      table.bidPackageId,
      table.deliveryChannel,
      table.normalizedDestination,
    ),
    index("bid_recipients_status_idx").on(table.bidPackageId, table.status),
    index("bid_recipients_contact_idx").on(table.contactId),
  ],
);

export const bidSubmissions = sqliteTable(
  "bid_submissions",
  {
    id: text("id").primaryKey(),
    bidPackageId: text("bid_package_id").notNull().references(() => bidPackages.id),
    bidRecipientId: text("bid_recipient_id").notNull().references(() => bidRecipients.id),
    portalAccountId: text("portal_account_id").references(() => portalAccounts.id, { onDelete: "set null" }),
    attempt: integer("attempt").notNull().default(1),
    deliveryChannel: text("delivery_channel").notNull(),
    providerKey: text("provider_key").notNull(),
    externalSubmissionId: text("external_submission_id"),
    idempotencyKey: text("idempotency_key").notNull(),
    approvalStatus: text("approval_status").notNull(),
    approvedBy: text("approved_by").notNull(),
    approvedAt: text("approved_at").notNull(),
    approvalEvidenceHash: text("approval_evidence_hash").notNull(),
    packageContentHash: text("package_content_hash").notNull(),
    payloadHash: text("payload_hash").notNull(),
    manifestHash: text("manifest_hash").notNull(),
    payloadObjectKey: text("payload_object_key").notNull(),
    immutableAt: text("immutable_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    submittedAt: text("submitted_at").notNull(),
    transportStatus: text("transport_status").notNull(),
    acceptanceStatus: text("acceptance_status").notNull().default("unknown"),
    receiptReference: text("receipt_reference"),
    receiptUrl: text("receipt_url"),
    receiptObjectKey: text("receipt_object_key"),
    receiptHash: text("receipt_hash"),
    receiptCapturedAt: text("receipt_captured_at"),
    responseCode: text("response_code"),
    providerResponseHash: text("provider_response_hash"),
    errorCode: text("error_code"),
    errorMessage: text("error_message"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("bid_submissions_idempotency_uidx").on(table.idempotencyKey),
    uniqueIndex("bid_submissions_attempt_uidx").on(table.bidPackageId, table.bidRecipientId, table.attempt),
    uniqueIndex("bid_submissions_external_uidx").on(table.providerKey, table.externalSubmissionId),
    index("bid_submissions_package_idx").on(table.bidPackageId, table.submittedAt),
    index("bid_submissions_status_idx").on(table.transportStatus, table.acceptanceStatus),
  ],
);

export const enrichmentRequests = sqliteTable(
  "enrichment_requests",
  {
    id: text("id").primaryKey(),
    providerKey: text("provider_key").notNull(),
    providerRequestId: text("provider_request_id"),
    idempotencyKey: text("idempotency_key").notNull(),
    contactId: text("contact_id").references(() => contacts.id, { onDelete: "set null" }),
    organizationId: text("organization_id").references(() => organizations.id, { onDelete: "set null" }),
    projectId: text("project_id").references(() => projects.id, { onDelete: "set null" }),
    requestedFields: text("requested_fields", { mode: "json" }).$type<string[]>().notNull(),
    inputHash: text("input_hash").notNull(),
    purpose: text("purpose").notNull(),
    legalBasis: text("legal_basis"),
    approvalStatus: text("approval_status").notNull().default("pending"),
    approvedBy: text("approved_by"),
    approvedAt: text("approved_at"),
    status: text("status").notNull().default("queued"),
    sourceUrl: text("source_url"),
    providerTermsVersion: text("provider_terms_version"),
    resultObjectKey: text("result_object_key"),
    resultHash: text("result_hash"),
    resultSummary: text("result_summary", { mode: "json" }).$type<Record<string, unknown>>(),
    resultConfidence: real("result_confidence"),
    verificationStatus: text("verification_status").notNull().default("unverified"),
    cost: real("cost"),
    requestedBy: text("requested_by"),
    requestedAt: text("requested_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    completedAt: text("completed_at"),
    expiresAt: text("expires_at"),
    error: text("error"),
  },
  (table) => [
    uniqueIndex("enrichment_requests_idempotency_uidx").on(table.idempotencyKey),
    uniqueIndex("enrichment_requests_provider_uidx").on(table.providerKey, table.providerRequestId),
    index("enrichment_requests_status_idx").on(table.status, table.requestedAt),
    index("enrichment_requests_contact_idx").on(table.contactId),
    index("enrichment_requests_organization_idx").on(table.organizationId),
  ],
);

export const outreachSuppressions = sqliteTable(
  "outreach_suppressions",
  {
    id: text("id").primaryKey(),
    suppressionKey: text("suppression_key").notNull(),
    supplierProfileId: text("supplier_profile_id").notNull().references(() => supplierProfiles.id, { onDelete: "cascade" }),
    contactId: text("contact_id").references(() => contacts.id, { onDelete: "set null" }),
    organizationId: text("organization_id").references(() => organizations.id, { onDelete: "set null" }),
    projectId: text("project_id").references(() => projects.id, { onDelete: "set null" }),
    channel: text("channel").notNull(),
    destinationHash: text("destination_hash").notNull(),
    destinationMasked: text("destination_masked"),
    scope: text("scope").notNull().default("global"),
    reason: text("reason").notNull(),
    source: text("source").notNull(),
    sourceReference: text("source_reference"),
    provenance: text("provenance", { mode: "json" }).$type<Record<string, unknown>>(),
    status: text("status").notNull().default("active"),
    effectiveAt: text("effective_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    expiresAt: text("expires_at"),
    createdBy: text("created_by"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("outreach_suppressions_key_uidx").on(table.suppressionKey),
    index("outreach_suppressions_destination_idx").on(table.destinationHash, table.channel, table.status),
    index("outreach_suppressions_profile_idx").on(table.supplierProfileId, table.status),
    index("outreach_suppressions_contact_idx").on(table.contactId),
  ],
);

export const bidActivityEvents = sqliteTable(
  "bid_activity_events",
  {
    id: text("id").primaryKey(),
    bidOpportunityId: text("bid_opportunity_id").notNull().references(() => bidOpportunities.id, { onDelete: "cascade" }),
    bidPackageId: text("bid_package_id").references(() => bidPackages.id, { onDelete: "set null" }),
    bidRecipientId: text("bid_recipient_id").references(() => bidRecipients.id, { onDelete: "set null" }),
    bidSubmissionId: text("bid_submission_id").references(() => bidSubmissions.id, { onDelete: "set null" }),
    contactId: text("contact_id").references(() => contacts.id, { onDelete: "set null" }),
    eventType: text("event_type").notNull(),
    actorType: text("actor_type").notNull(),
    actorId: text("actor_id"),
    sourceSystem: text("source_system").notNull(),
    sourceEventId: text("source_event_id"),
    previousStatus: text("previous_status"),
    newStatus: text("new_status"),
    payload: text("payload", { mode: "json" }).$type<Record<string, unknown>>(),
    payloadHash: text("payload_hash").notNull(),
    dedupeKey: text("dedupe_key"),
    occurredAt: text("occurred_at").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("bid_activity_events_dedupe_uidx").on(table.dedupeKey),
    uniqueIndex("bid_activity_events_source_uidx").on(table.sourceSystem, table.sourceEventId),
    index("bid_activity_events_opportunity_idx").on(table.bidOpportunityId, table.occurredAt),
    index("bid_activity_events_package_idx").on(table.bidPackageId),
    index("bid_activity_events_submission_idx").on(table.bidSubmissionId),
  ],
);

/**
 * Durable, on-demand research cache. A row is intentionally scoped by
 * (project, visibility) so opening the same known project cannot fan out into
 * duplicate network jobs. Findings are evidence records rather than inferred
 * CRM data; promotion into canonical contacts/documents remains a separate,
 * reviewable operation.
 */
export const projectResearchJobs = sqliteTable(
  "project_research_jobs",
  {
    id: text("id").primaryKey(),
    projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
    cacheKey: text("cache_key").notNull(),
    visibility: text("visibility").notNull().default("workspace"),
    status: text("status").notNull().default("queued"),
    requestedBy: text("requested_by").notNull(),
    trigger: text("trigger").notNull().default("project-open"),
    attempt: integer("attempt").notNull().default(0),
    maxAttempts: integer("max_attempts").notNull().default(3),
    requestedAt: text("requested_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    startedAt: text("started_at"),
    completedAt: text("completed_at"),
    freshUntil: text("fresh_until"),
    nextRetryAt: text("next_retry_at"),
    leaseOwner: text("lease_owner"),
    leaseExpiresAt: text("lease_expires_at"),
    publicApprovedAt: text("public_approved_at"),
    publicApprovedBy: text("public_approved_by"),
    errorCode: text("error_code"),
    errorMessage: text("error_message"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("project_research_jobs_cache_uidx").on(table.cacheKey),
    index("project_research_jobs_project_idx").on(table.projectId, table.visibility),
    index("project_research_jobs_due_idx").on(table.status, table.nextRetryAt, table.leaseExpiresAt),
    index("project_research_jobs_fresh_idx").on(table.freshUntil),
  ],
);

export const projectResearchFindings = sqliteTable(
  "project_research_findings",
  {
    id: text("id").primaryKey(),
    researchJobId: text("research_job_id").notNull().references(() => projectResearchJobs.id, { onDelete: "cascade" }),
    projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
    category: text("category").notNull(),
    findingType: text("finding_type").notNull(),
    dedupeKey: text("dedupe_key").notNull(),
    data: text("data", { mode: "json" }).$type<Record<string, unknown>>().notNull(),
    sourceId: text("source_id").references(() => sources.id, { onDelete: "set null" }),
    sourceUrl: text("source_url").notNull(),
    sourceLabel: text("source_label"),
    evidence: text("evidence").notNull(),
    provenance: text("provenance", { mode: "json" }).$type<Record<string, unknown>>().notNull(),
    confidence: real("confidence").notNull(),
    observedAt: text("observed_at").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("project_research_findings_dedupe_uidx").on(table.researchJobId, table.dedupeKey),
    index("project_research_findings_project_idx").on(table.projectId, table.category),
    index("project_research_findings_job_idx").on(table.researchJobId),
  ],
);

export const projectResearchGaps = sqliteTable(
  "project_research_gaps",
  {
    id: text("id").primaryKey(),
    researchJobId: text("research_job_id").notNull().references(() => projectResearchJobs.id, { onDelete: "cascade" }),
    projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
    gapType: text("gap_type").notNull(),
    status: text("status").notNull().default("open"),
    message: text("message").notNull(),
    nextAction: text("next_action"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("project_research_gaps_type_uidx").on(table.researchJobId, table.gapType),
    index("project_research_gaps_project_idx").on(table.projectId, table.status),
  ],
);

export const projectResearchSourceAttempts = sqliteTable(
  "project_research_source_attempts",
  {
    id: text("id").primaryKey(),
    researchJobId: text("research_job_id").notNull().references(() => projectResearchJobs.id, { onDelete: "cascade" }),
    projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
    sourceId: text("source_id").references(() => sources.id, { onDelete: "set null" }),
    sourceUrl: text("source_url").notNull(),
    finalUrl: text("final_url"),
    status: text("status").notNull(),
    httpStatus: integer("http_status"),
    contentType: text("content_type"),
    bytesRead: integer("bytes_read").notNull().default(0),
    durationMs: integer("duration_ms").notNull().default(0),
    errorCode: text("error_code"),
    errorMessage: text("error_message"),
    startedAt: text("started_at").notNull(),
    completedAt: text("completed_at").notNull(),
  },
  (table) => [
    index("project_research_attempts_job_idx").on(table.researchJobId, table.startedAt),
    index("project_research_attempts_project_idx").on(table.projectId, table.status),
  ],
);

export const projectResearchHandoffs = sqliteTable(
  "project_research_handoffs",
  {
    id: text("id").primaryKey(),
    researchJobId: text("research_job_id").notNull().references(() => projectResearchJobs.id, { onDelete: "cascade" }),
    projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
    findingId: text("finding_id").references(() => projectResearchFindings.id, { onDelete: "set null" }),
    handoffType: text("handoff_type").notNull(),
    status: text("status").notNull().default("awaiting-extractor"),
    sourceUrl: text("source_url").notNull(),
    detail: text("detail").notNull(),
    requestedAt: text("requested_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("project_research_handoffs_source_uidx").on(table.researchJobId, table.handoffType, table.sourceUrl),
    index("project_research_handoffs_status_idx").on(table.status, table.updatedAt),
    index("project_research_handoffs_project_idx").on(table.projectId),
  ],
);

/**
 * Per-user provider credentials. Secrets are encrypted by the application with
 * AES-256-GCM before they reach D1. The owner/provider tuple is also bound into
 * the authenticated ciphertext so rows cannot be moved between accounts or
 * providers and still decrypt.
 */
export const integrationCredentials = sqliteTable(
  "integration_credentials",
  {
    id: text("id").primaryKey(),
    ownerKey: text("owner_key").notNull(),
    provider: text("provider").notNull(),
    encryptedSecret: text("encrypted_secret").notNull(),
    iv: text("iv").notNull(),
    keyVersion: integer("key_version").notNull().default(1),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("integration_credentials_owner_provider_uidx").on(
      table.ownerKey,
      table.provider,
    ),
    index("integration_credentials_owner_idx").on(table.ownerKey),
  ],
);
